#!/bin/bash

. /etc/default/frontend

FRONTEND=$(echo $UPSTART_JOB | sed 's/frontend-//')

echo $FRONTEND > /tmp/x

master_start() {
  CHECK_STATUS=$(initctl status frontend-$DEFAULT_FRONTEND)
  if [[ "$CHECK_STATUS" == *waiting* ]]; then
    initctl start frontend-$DEFAULT_FRONTEND
  fi
}

master_stop() {
  CHECK_STATUS=$(initctl status frontend-$DEFAULT_FRONTEND)
  if [[ "$CHECK_STATUS" == *running* ]]; then
    initctl stop frontend-$DEFAULT_FRONTEND
  fi
}

prestart() {
  # stop other frontends
  if [ -f /tmp/active-frontend ]; then
    STARTED_FRONTEND=$(cat /tmp/active-frontend)

    CHECK_STATUS=$(initctl status frontend-$STARTED_FRONTEND)
    if [[ "$CHECK_STATUS" == *running* ]]; then
      initctl stop frontend-$STARTED_FRONTEND
    fi
  fi

  echo "$FRONTEND" > /tmp/active-frontend

  # sync job status to frontend if this default frontend
  if [ "$DEFAULT_FRONTEND" = "$FRONTEND" ]; then
    CHECK_STATUS=$(initctl status frontend)
    if [[ "$CHECK_STATUS" == *waiting* ]]; then
      initctl start frontend
    fi
  fi

}

poststop() {

  # sync job status to frontend if this default frontend
  if [ "$DEFAULT_FRONTEND" = "$FRONTEND" ]; then
    CHECK_STATUS=$(initctl status frontend)
    if [[ "$CHECK_STATUS" == *running* ]]; then
      initctl stop frontend
    fi
  fi

  # clear frontend
  echo "" > /tmp/active-frontend
}
