#!/bin/bash

prestart() {
  if [ -f /tmp/active-frontend ]; then
    STARTED_FRONTEND=$(cat /tmp/active-frontend)
    if [ "$STARTED_FRONTEND" != "" ]; then
      initctl stop $STARTED_FRONTEND
    fi
  fi
  echo "$UPSTART_JOB" > /tmp/active-frontend
}

poststop() {
  echo "" > /tmp/active-frontend
}
