#!/bin/sh -e

/usr/bin/process-template --owner root --group root --mode 0644 /etc/yavdr/vdr/plugins/plugin.softhddevice.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/yavdr/vdr/plugins.conf

