#!/bin/bash -e

/usr/bin/process-template --owner root --group root --mode 0644 /etc/vdr/plugins/plugin.softhddevice.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/vdr/plugins/order.conf

