#!/bin/sh -e

case "$1" in
  configure)

  # prefill hdf
  . /usr/share/yavdr/helpers/hdf_prefill
  hdf_prefill "frontend.default" "softhddevice"

  # temlate files
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/vdr/plugins/plugin.softhddevice.conf
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/vdr/plugins/order.conf
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/default/frontend

  ;;

esac

exit 0

