#!/bin/bash -e

case "$1" in
  configure)

  # prefill hdf
  yavdr-db-tool -k frontend.default -a preset -v "dummy"
  yavdr-db-tool -k system.display.0.active -a preset -v "1"
  yavdr-db-tool -k system.display.0.rate -a preset -v "50"
  yavdr-db-tool -k system.display.0.width -a preset -v "1920"
  yavdr-db-tool -k system.display.0.height -a preset -v "1080"

  # temlate files
  yavdr-template-frontend

  ;;

esac

exit 0

