#!/bin/sh -e

logger -t yavdr-template-frontend "templating"
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/openbox.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/openbox-second.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/X11/xorg.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/frontend.conf

for FRONTEND in `yavdr-list-frontend-modules`; do
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/frontend-$FRONTEND.conf
  if [ -f /usr/bin/_yavdr-template-frontend-$FRONTEND ]; then
    /usr/bin/_yavdr-template-frontend-$FRONTEND
  fi
done
