#!/bin/bash -e

/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/openbox.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/openbox-second.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/X11/xorg.conf
/usr/bin/process-template --owner root --group root --mode 0644 /etc/default/frontend
/usr/bin/process-template --owner root --group root --mode 0644 /etc/init/frontend.conf

cd /usr/share/yavdr/frontends/
for FRONTEND in *; do
  /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/frontend-$FRONTEND.conf
  if [ -f /usr/bin/yavdr-template-frontend-$FRONTEND ]; then
    /usr/bin/yavdr-template-frontend-$FRONTEND
  fi
done
