    Option         "NoPM" "true"
    Option         "blank time" "0"
    Option         "standby time" "0"
    Option         "suspend time" "0"
    Option         "off time" "0"
    Option         "Xinerama" "0"
